[Oy2-19473] Create Logo Component
CMSgov/macpro-ux-lib pull request #36
Opened 2022-07-27 20:39 UTC by jphechter

## Purpose

Create a new Logo component.

## Type of Request

feature

## Approach

Tried to follow existing patterns established in other components.

## Assorted Notes/Considerations

Because this component is dealing primarily with images, I included 2 new image files (an SVG and PNG of CMS.gov logo) to be used in the Storybook implementation. Additionally, Jest does not process images well, so there is a new transform module `imgTransform.js` that is called whenever Jest imports an SVG or PNG file. This is generic and can be extended to cover other file types.

#### Pull Request Creator Checklist

- [X] It is documented what type of request this is.
- [X] There is a detailed description for the purpose of this PR.
- [X] This PR is in line with the intention of this Project

2022-07-29 17:01 UTC, jdinh8124 requested changes
Looks good for the most part, had some small comments

2022-07-29 17:01 UTC, jdinh8124 commented on src/components/Logo/Logo.tsx
> +      className={`application-logo-container ${className}`}
Maybe some sort of check here in the change its undefined

`${className ??  ""}` or `${classname? className : ""}`

2022-08-01 15:35 UTC, jphechter commented on src/components/Logo/Logo.stories.tsx
> +    },
🤦‍♂️

2022-08-01 17:42 UTC, jdinh8124 approved these changes
Looks good to me!

2022-08-01 19:40 UTC, merged