Oy2 19467 - Footer component
CMSgov/macpro-ux-lib pull request #61
Opened 2022-08-09 20:57 UTC by jdinh8124

## Purpose
- Create react footer component based on figma designs and USWDS
Resolves:
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/240?modal=detail&selectedIssue=OY2-19467

#### Pull Request Creator Checklist

- [x] It is documented what type of request this is.
- [x] There is a detailed description for the purpose of this PR.
- [x] This PR is in line with the intention of this Project

2022-08-10 14:40 UTC, jdinh8124 commented on src/components/Footer/Footer.tsx
> +
I see JP is having an incoming interface thats similar maybe we can export one of them

2022-08-10 14:42 UTC, jdinh8124 commented on src/components/Footer/Footer.tsx
> +
I see JP is having an incoming interface thats similar maybe we can export one of them

2022-08-10 18:46 UTC, jphechter requested changes
1 note about the story implementation, other than that LGTM 👍 

I did run the tests locally just to check coverage. Noticed that the images added in this PR are getting picked up for some reason. I tried updating `jest.config.ts` adding `assets` to both `coveragePathIgnorePatterns` and `testPathIgnorePatterns`. Neither seemed to work.
<img width="765" alt="Screen Shot 2022-08-10 at 2 28 55 PM" src="https://user-images.githubusercontent.com/22647707/183991292-f6c03f02-b5c2-452e-bcc6-6d65db960099.png">
 Their coverage is at 100% 🙃 so I don't really see an issue. Just something interesting.

2022-08-10 18:46 UTC, jphechter commented on src/components/Footer/Footer.stories.tsx
> +    },
```suggestion
    navigationLinks: {
      description:
        "Array of navigation elements to render in the alternative footer",
        control: false,
    },
```
I think this is a good candidate for control to disable in Storybook.

2022-08-11 15:10 UTC, jphechter approved these changes

2022-08-11 15:30 UTC, merged